name: tester

on:
  workflow_dispatch:    
    inputs:
      target_commit_sha:
        description: 'The commit SHA on this repo to use for the Soak Tests.'
        required: true
      test_duration_minutes:
        description: 'The duration of the Soak Tests in minutes.'
        required: true
        default: "300"

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Use INPUT as commit SHA
        env:
          SHA: ${{ github.event.pull_request.title }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "TARGET_SHA=$SHA" | tee --append $GITHUB_ENV;
          echo $TARGET_SHA
      - name: Configure Performance Test Duration
        env:
          DURATION: ${{ github.event.inputs.test_duration_minutes }}
        run: |
          echo "TEST_DURATION_MINUTES=${{ $DURATION || env.DEFAULT_TEST_DURATION_MINUTES }}" | tee --append $GITHUB_ENV;
          echo $TEST_DURATION_MINUTES
