name: tester

on:
  workflow_dispatch:    
    inputs:
      target_commit_sha:
        description: 'The commit SHA on this repo to use for the Soak Tests.'
        required: true
      test_duration_minutes:
        description: 'The duration of the Soak Tests in minutes.'

env:
  DEFAULT_TEST_DURATION_MINUTES: 300

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Use INPUT as commit SHA
        env:
          TARGET_SHA: ${{ github.event.inputs.target_commit_sha }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo $TARGET_SHA
      - name: Configure Performance Test Duration
        env:
          TEST_DURATION_MINUTES: ${{ github.event.inputs.test_duration_minutes || env.DEFAULT_TEST_DURATION_MINUTES }}
        run: |
          echo $TEST_DURATION_MINUTES
